aws_region               = "us-east-2"
db_instance_identifier   = "my-rds"
allocated_storage        = 20
storage_type             = "gp2"
engine                   = "mysql"
engine_version           = "8.0"
instance_class           = "db.t3.micro"
db_name                  = "mydatabase"
db_username              = "admin"
db_password              = "12345678"
parameter_group_name     = "default.mysql8.0"
publicly_accessible      = true
public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD3F6tyPEFEzV0LX3X8BsXdMsQz1x2cEikKDEY0aIj41qgxMCP/iteneqXSIFZBp5vizPvaoIR3Um9xK7PGoW8giupGn+EPuxIA4cDM4vzOqOkiMPhz5XK0whEjkVzTo4+S0puvDZuwIsdiW9mxhJc7tgBNL0cYlWSYVkz4G/fslNfRPW5mYAM49f4fhtxPb5ok4Q2Lg9dPKVHO/Bgeu5woMc7RY0p1ej6D4CKFE6lymSDJpW0YHX/wqE9+cfEauh7xZcG0q9t2ta6F6fmX0agvpFyZo8aFbXeUBr7osSCJNgvavWbM/06niWrOvYX2xwWdhXmXSrbX8ZbabVohBK41 email@example.com"
key_name   = "Final-key"
